---
apiVersion: v1
kind: Secret
metadata:
  name: user4-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/backstage-mh5sz/user4-gateway-gitops
